Repository puppetlabs/vmpooler-provider-vsphere, pull requests merged in 2023-08, with the labels that each got.

#40 Bump jruby to 9.4.3.0 and update lockfile
  .github/workflows/release.yml
  .github/workflows/testing.yml
  Gemfile.lock
  install-gemfile-lock
  release-prep
  update-gemfile-lock
Labels: enhancement

#41 3.2.0 release prep
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler-provider-vsphere/version.rb
Labels: maintenance

#42 (POD-10) Log reason for failed VM checks.
  lib/vmpooler/providers/vsphere.rb
  spec/unit/providers/vsphere_spec.rb
Labels: enhancement

#43 (maint) Release prep for version 3.3.0
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler-provider-vsphere/version.rb
Labels: maintenance

#44 (RE-15710) Fix IP address that is returned and increase timeout
  lib/vmpooler/providers/vsphere.rb
  spec/rbvmomi_helper.rb
  spec/unit/providers/vsphere_spec.rb
Labels: bug

#50 (maint) Release prep for version 3.3.3
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler-provider-vsphere/version.rb
Labels: maintenance

#51 (maint) Convert booleans and Time objects to strings when being added to redis
  lib/vmpooler/providers/vsphere.rb
Labels: bug

#52 (maint) Release prep for version 3.3.4
  CHANGELOG.md
  Gemfile.lock
  lib/vmpooler-provider-vsphere/version.rb
Labels: maintenance
